name: instagram
description: "A new Flutter project."

publish_to: 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.3.3
  provider:
  url_launcher: ^6.3.1
  form_field_validator: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
